#!/bin/sh
git config --global core.editor "vim"
git config --global core.commentChar ";"
git config --global alias.log2 "log --oneline --graph --decorate"
git config --global alias.log3 "log --format='[%H]%s'"
git config --global alias.merge2 "merge --no-ff"
git config --global alias.smerge "merge --squash"
git config --global alias.sdiff "diff --name-only"
git config --global alias.sdiffs "diff --name-only --staged"
git config --global alias.sdiffc "diff --name-only --cached"
git config --global alias.diffs "diff --staged"
git config --global alias.diffc "diff --cached"
